### ISSUE TITLE
Initialisation du repository

### ISSUE THREAD

**Issue by ZeTilt** [ZeTilt/LeBonTiming#1]
- [ ] Création de la branche develop
- [ ] Set develop comme branche par défaut
- [ ] Création d'une branche preprod basée sur develop
- [ ] Création d'une branche prod basée sur preprod
